# Generated by Django 5.2.4 on 2025-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingtext',
            name='content',
        ),
        migrations.AddField(
            model_name='readingtext',
            name='english_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingtext',
            name='urdu_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingtext',
            name='date',
            field=models.DateField(),
        ),
    ]
